### ISSUE TITLE
How to solve the warning: index 1010 is out of bounds for axis 0 with size 412

### ISSUE THREAD

**Issue by kelesy923** [lgzlIlIlI/BiSCC#2]

**Comment by lgzlIlIlI** [comment]
You should using annotations from ./Thumos14reduced-Annotations rather than ./Thumos14-Annotations

**Comment by kelesy923** [comment]
Thanks， How to get the itemp_anno load data temp_label

**Comment by lgzlIlIlI** [comment]
The temp_label is not the necessary file for training and testing, and you can remove it in the code
