### ISSUE TITLE
could you please also share your training code? I also want to follow your work

### ISSUE THREAD

**Issue by YukiFan** [lgzlIlIlI/BiSCC#3]
if you are busy with other more important things, can you also share your code with email?
thank you very much! this is my email: fyd_ly@163.com

**Comment by lgzlIlIlI** [comment]
Hello,
The code, dataset and the checkpoint of this work can be get from https://pan.baidu.com/s/179b1jIJKPtdPFSlN18-coA (aenq)

**Comment by YukiFan** [comment]
thank you very much

**Comment by xuxiaoyihrgtg** [comment]
> Hello, The code, dataset and the checkpoint of this work can be get from https://pan.baidu.com/s/179b1jIJKPtdPFSlN18-coA (aenq)
There are only data sets and pre-training files, can you share the code for the training part?

**Comment by lgzlIlIlI** [comment]
Hi, The code of this work can be get from https://pan.baidu.com/s/179b1jIJKPtdPFSlN18-coA (aenq)
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/26/2023 17:11
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Guozhang ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [lgzlIlIlI/BiSCC] could you please also share your training code? I also want to follow your work (Issue #3)
        
      
    
  


Hello, The code, dataset and the checkpoint of this work can be get from https://pan.baidu.com/s/179b1jIJKPtdPFSlN18-coA (aenq)
There are only data sets and pre-training files, can you share the code for the training part?

**Comment by xuxiaoyihrgtg** [comment]
> Hi, The code of this work can be get from https://pan.baidu.com/s/179b1jIJKPtdPFSlN18-coA (aenq) ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 10/26/2023 17:11 To ***@***.***> Cc Guozhang ***@***.***> , ***@***.***> Subject Re: [lgzlIlIlI/BiSCC] could you please also share your training code? I also want to follow your work (Issue #3) Hello, The code, dataset and the checkpoint of this work can be get from https://pan.baidu.com/s/179b1jIJKPtdPFSlN18-coA (aenq) There are only data sets and pre-training files, can you share the code for the training part? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Sorry, the link is no longer available, could you please share another copy
